version: '2.3'
services:
  filebeat:
    build: ${PWD}/../filebeat/.
    depends_on:
      - proxy_dep
    environment:
      - BEAT_STRICT_PERMS=false
      - KIBANA_HOST=kibana
      - KIBANA_PORT=5601
      - KIBANA_USER=beats
      - KIBANA_PASS=testing
      - ES_PORT=9200
      - ES_KERBEROS_HOST=elasticsearch_kerberos.elastic
      - ES_SUPERUSER_USER=admin
      - ES_SUPERUSER_PASS=changeme
    volumes:
      - ${PWD}/..:/go/src/github.com/elastic/beats/
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /go/src/github.com/elastic/beats/filebeat
    command: ./demo.sh

  proxy_dep:
    image: busybox
    depends_on:
      elasticsearch_kerberos.elastic: { condition: service_healthy }
    healthcheck:
      interval: 1s
      retries: 1200

  elasticsearch_kerberos.elastic:
    build: ${ES_BEATS}/testing/environments/docker/elasticsearch_kerberos
    healthcheck:
      test: bash -c "/healthcheck.sh"
      retries: 1200
      interval: 5s
      start_period: 60s
    environment:
      - "TERM=linux"
      - "ELASTIC_PASSWORD=changeme"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Djava.security.krb5.conf=/etc/krb5.conf"
      - "network.host="
      - "transport.host=127.0.0.1"
      - "http.host=0.0.0.0"
      - "xpack.security.enabled=true"
      - "indices.id_field_data.enabled=true"
      - "xpack.license.self_generated.type=trial"
      - "xpack.security.authc.realms.kerberos.ELASTIC.order=1"
      - "xpack.security.authc.realms.kerberos.ELASTIC.keytab.path=/usr/share/elasticsearch/config/HTTP_elasticsearch_kerberos.elastic.keytab"
    hostname: elasticsearch_kerberos.elastic
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random
    ports:
      - 1088
      - 1749
      - 9200
    command: bash -c "/start.sh"
